# Generated by Django 2.2.4 on 2019-10-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VoltsBackEnd', '0022_auto_20191017_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransID', models.CharField(max_length=20)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('TransTime', models.CharField(max_length=30, verbose_name='The time mpesa received payment')),
                ('MSISDN', models.PositiveIntegerField()),
                ('TransAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('MiddleName', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MpesaOrders', to='VoltsBackEnd.Order')),
            ],
        ),
    ]
