# Generated by Django 2.2.4 on 2019-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0002_auto_20190827_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products-images/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumb',
            field=models.ImageField(upload_to='products-thumbs/', verbose_name='Product Image Thumbnail'),
        ),
    ]
