# Generated by Django 2.2.4 on 2019-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0004_productsubcategory_subcategory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='subcategory_photo',
            field=models.ImageField(upload_to='card-categories-images/', verbose_name='image on the homepage categories'),
        ),
    ]
