# Generated by Django 2.2.4 on 2019-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0005_auto_20190922_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cart_quantity',
            field=models.IntegerField(default=1, verbose_name='Minimum cart quantity'),
        ),
    ]
