# Generated by Django 2.2.4 on 2019-10-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0007_auto_20191006_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Last Name'),
        ),
    ]
