# Generated by Django 2.2.4 on 2019-10-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0008_auto_20191007_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_line_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
