# Generated by Django 2.2.4 on 2019-10-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0009_auto_20191007_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
