# Generated by Django 2.2.4 on 2019-10-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0010_customer_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organisation_or_person',
            field=models.CharField(choices=[('O', 'Organisation'), ('P', 'Person')], default='P', max_length=2),
        ),
    ]
