# Generated by Django 2.2.4 on 2019-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0011_auto_20191007_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_customer_instruction',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
