# Generated by Django 2.2.4 on 2019-10-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0012_auto_20191007_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='RMA_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
