# Generated by Django 2.2.4 on 2019-10-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0014_auto_20191007_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='VoltsBackEnd.Customer'),
        ),
    ]
