# Generated by Django 2.2.4 on 2019-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0015_auto_20191007_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order_placed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
