# Generated by Django 2.2.4 on 2019-10-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0018_auto_20191007_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('D', 'Delivered'), ('C', 'Cancelled'), ('O.R', 'On Route'), ('N.D', 'Not Delivered')], default='N.D', max_length=5),
        ),
    ]
