# Generated by Django 2.2.4 on 2019-10-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0019_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status_Code',
        ),
        migrations.DeleteModel(
            name='RefOrderStatusCodes',
        ),
    ]
