# Generated by Django 2.2.4 on 2019-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoltsBackEnd', '0021_auto_20191008_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Phone Number'),
        ),
    ]
