export const GET_PRODUCTS_CATEGORIES = 'GET_PRODUCTS_CATEGORIES';
export const GET_SUBCATEGORY_PRODUCTS = 'GET_SUBCATEGORY_PRODUCTS';
export const GET_SUBCATEGORY_PRODUCTS_BY_NAME = 'GET_SUBCATEGORY_PRODUCTS_BY_NAME';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CREATE_ORDER_STATE = 'CREATE_ORDER_STATE';
export const ORDER_RES = 'ORDER_RES';
